# Generated by Django 5.2.7 on 2025-10-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_cliente', models.CharField(max_length=10, unique=True, verbose_name='Run Cliente')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mascotas.mascotas')),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mascotas.cliente')),
            ],
        ),
    ]
