# Generated by Django 5.2.7 on 2025-10-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascotas_foto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
